### ISSUE TITLE
I'd like to search for rsIDs

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform_issues#26] opened 2017-03-29 15:36 UTC
This request has last been made by Nizar Smaoui at Platform training session for Takeda. It's been requested by other workshops' attendees as well.

**Comment by emepyc** [comment] 2017-03-29 15:48
Not clear to me what to expect from a genomic coordinate search... targets? snps? other entities? disease enrichment? mixed of all of them? what is the limit of a the genomic chunk to query? How would a result page look like?
We also try to be as assembly agnostic as possible. This breaks that (we don't have genomic coordinates in the backend at all for now).
Maybe this issue should be broken in 2: it is more clear to know what a rsID search would look like. Genomic coordinates is much more complex.

**Comment by deniseOme** [comment] 2017-03-29 16:25
This was also a question from Eric Lai (takeda) at previous conversation with @elipapa

**Comment by elipapa** [comment] 2017-09-14 22:58
duplicate of https://github.com/opentargets/features/issues/12

**Closed by elipapa** 2017-09-14 22:58 UTC
Labels: enhancement, user request, workshop feedback (written or spoken)
